#!/bin/sh
#
# openshift-load-balancer-daemon:        Starts the load-balancer configuration
# daemon for OpenShift.
#
# chkconfig: 345 85 15
# description:  This is a daemon which listens for notifications of \
#   application lifecycle events on ActiveMQ from the OpenShift \
#   routing plug-in and configures an external load-balancer \
#   appropriately.
#
# processname: ruby
# config: /etc/openshift/load-balancer.conf
# pidfile: /var/run/openshift-load-balancer-daemon.pid
#

### BEGIN INIT INFO
# Required-Start: $local_fs $network $named
# Required-Stop: $local_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Starts the load-balancer daemon for OpenShift
# Description: This is a daemon which listens for notifications of
#               application lifecycle events on ActiveMQ from the
#               OpenShift routing plug-in and configures an external
#               load-balancer appropriately.
### END INIT INFO

base='openshift-load-balancer-daemon'

[ -f /etc/openshift/load-balancer.conf ] || exit 6
[ -x /usr/sbin/openshift-load-balancer-daemon ] || exit 6

# Source function library.
. /etc/rc.d/init.d/functions

start() {
    echo -n $"Starting OpenShift Load Balancer Daemon: "
    /usr/sbin/openshift-load-balancer-daemon start
    RETVAL=$?
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/openshift-load-balancer-daemon && success $"$base startup" || failure $"$base startup"
    echo
}

stop() {
    echo -n $"Stopping OpenShift Load Balancer Daemon: "
    /usr/sbin/openshift-load-balancer-daemon stop
    RETVAL=$?
    [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/openshift-load-balancer-daemon && success $"$base shutdown" || failure $"$base shutdown"
    echo
}

# See how we were called.
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        /usr/sbin/openshift-load-balancer-daemon status
        RETVAL=$?
        ;;
    reload|restart|force-reload)
        stop
        start
        ;;
    condrestart|try-restart)
        if [ -f /var/run/openshift-load-balancer-daemon.pid ]
        then
            stop
            start
        fi
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|force-reload|condrestart|try-restart|reload}"
        exit 2
esac
exit $RETVAL
